---
includes:
  - docs/reqstream/review-mark.yaml
  - docs/reqstream/review-mark/platform-requirements.yaml
  - docs/reqstream/review-mark/program.yaml
  - docs/reqstream/review-mark/cli.yaml
  - docs/reqstream/review-mark/cli/context.yaml
  - docs/reqstream/review-mark/configuration.yaml
  - docs/reqstream/review-mark/configuration/review-mark-configuration.yaml
  - docs/reqstream/review-mark/configuration/glob-matcher.yaml
  - docs/reqstream/review-mark/indexing.yaml
  - docs/reqstream/review-mark/indexing/review-index.yaml
  - docs/reqstream/review-mark/indexing/path-helpers.yaml
  - docs/reqstream/review-mark/self-test.yaml
  - docs/reqstream/review-mark/self-test/validation.yaml
  - docs/reqstream/ots/xunit.yaml
  - docs/reqstream/ots/reviewmark.yaml
  - docs/reqstream/ots/reqstream.yaml
  - docs/reqstream/ots/buildmark.yaml
  - docs/reqstream/ots/versionmark.yaml
  - docs/reqstream/ots/sarifmark.yaml
  - docs/reqstream/ots/sonarmark.yaml
  - docs/reqstream/ots/pandoc.yaml
  - docs/reqstream/ots/weasyprint.yaml
  - docs/reqstream/ots/fileassert.yaml
  - docs/reqstream/ots/dema-consulting-test-results.yaml
  - docs/reqstream/ots/microsoft-extensions-file-system-globbing.yaml
  - docs/reqstream/ots/pdfsharp.yaml
  - docs/reqstream/ots/yamldotnet.yaml
