package ReviewMark {
    part def ReviewMarkConfiguration {
        doc /* YAML configuration parser and review-set processor. */

        comment sourceRef /* Source: src/DemaConsulting.ReviewMark/Configuration/ReviewMarkConfiguration.cs */
        comment testRef /* Test: test/DemaConsulting.ReviewMark.Tests/Configuration/ReviewMarkConfigurationTests.cs */
        comment designRef /* Design: docs/design/review-mark/configuration/review-mark-configuration.md */
        comment verificationRef /* Verification: docs/verification/review-mark/configuration/review-mark-configuration.md */
        comment reqRef /* Requirements: docs/reqstream/review-mark/configuration/review-mark-configuration.yaml */
    }
}
