---
blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/demaconsulting/ReviewMark
    about: Read the documentation for ReviewMark
  - name: 💬 Discussions
    url: https://github.com/demaconsulting/ReviewMark/discussions
    about: Ask questions and discuss with the community
