package ReviewMark {
    part def Validation {
        doc /* Self-validation test runner. */

        comment sourceRef /* Source: src/DemaConsulting.ReviewMark/SelfTest/Validation.cs */
        comment testRef /* Test: test/DemaConsulting.ReviewMark.Tests/SelfTest/ValidationTests.cs */
        comment designRef /* Design: docs/design/review-mark/self-test/validation.md */
        comment verificationRef /* Verification: docs/verification/review-mark/self-test/validation.md */
        comment reqRef /* Requirements: docs/reqstream/review-mark/self-test/validation.yaml */
    }
}
